# -*- coding: utf-8 -*-
#
# Micro documentation build configuration file, created by
# sphinx-quickstart on Wed Sep 16 18:33:49 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import shlex

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.pngmath',
    'sphinxcontrib.bibtex',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Micro'
copyright = u'2016, Jakub Macků'
author = u'Jakub Macků'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.0.1'
# The full version, including alpha/beta/rc tags.
release = '1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'cs'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {
#  'show_related': 'true',
#}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'microdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
'papersize': 'a4paper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '12pt',
'classoptions': ',openany,oneside',				# volne stranky
'babel': '\\usepackage[czech]{babel}',

# Additional stuff for the LaTeX preamble.
'preamble': '\\setcounter{tocdepth}{3} \n \
\\usepackage{graphicx}',	
#zacatek
'maketitle': u'%% Obalka - zacatek%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
\\newcommand\\textbox[1]{% \n \
  \\parbox{.5\\textwidth}{#1}% \n \
} \n \
\\begin{center} \n \
\\textsf{\\textsc{\\textcolor{black}{\\Large{ GYMNÁZIUM A ZUŠ ŠLAPANICE }}}} \n \
\\par\end{center} \n \
\\vspace{2.5cm} \n \
\\begin{center} \n \
\\includegraphics[scale=0.3]{logo} \n \
\\par\\end{center} \n \
\\vspace{2.5cm} \n \
\\begin{center} \n \
\\textsf{\\textbf{\\Huge{DIGITÁLNÍ ZPRACOVÁNÍ MIKROSKOPOVÝCH OBRAZŮ}}} \n \
\\par\\end{center} \n \
\\vspace{8cm} \n \
\\begin{center} \n \
\\textsf{\\textbf{ŠLAPANICE}} \n \
\\par\\end{center} \n \
\\vspace{4cm} \n \
\\begin{flushleft} \n \
\\textsf{\\textbf{2016/2017\\hfill\\hfill JAKUB MACKŮ}} \n \
\\par\\end{flushleft} \n \
\\newpage \n \
%% Obálka - konec%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
%% Titulní strana - zacatek%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
\\begin{center} \n \
\\textsf{\\textsc{\\textcolor{black}{\\Large{ ROČNÍKOVÁ PRÁCE }}}} \n \
\\par\\end{center} \n \
\\vspace{0.5cm} \n \
\\begin{center} \n \
\\textsf{\\textsc{\\textcolor{black}{\\Large{ Obor: Informatika }}}} \n \
\\par\\end{center} \n \
\\vspace{2.5cm} \n \
\\begin{center} \n \
\\textsf{\\textbf{\\Huge{DIGITÁLNÍ ZPRACOVÁNÍ MIKROSKOPOVÝCH OBRAZŮ}}} \n \
\\par\\end{center} \n \
\\begin{center} \n \
\\vspace{1cm} \n \
\\textsf{\\textbf{\\Large{Digital processing of microscopical images}}} \n \
\\par\\end{center} \n \
\\vspace{5cm} \n \
\\begin{center} \n \
\\textsf{\\textsc{\\textcolor{black}{\\Large{ GYMNÁZIUM A ZUŠ ŠLAPANICE }}}} \n \
\\par\\end{center} \n \
\\vspace{5cm} \n \
\\begin{center} \n \
\\textsf{\\textbox{\\begin{center}VEDOUCÍ PRÁCE: \\end{center}}\\textbox{\\begin{center}AUTOR: \\end{center}}} \n \
\\textsf{\\textbox{\\begin{center}Mgr. Roman Ondrůšek \\end{center}}\\textbox{\\begin{center}Jakub Macků \\end{center}}} \n \
\\par\\end{center} \n \
\\begin{center} \n \
\\vspace{2cm} \n \
\\textsf{\\textsc{\\textcolor{black}{{Šlapanice}}}} \n \
\\par\\end{center} \n \
\\begin{center} \n \
\\textsf{\\textsc{\\textcolor{black}{{2016/2017}}}} \n \
\\par\\end{center} \n \
\\newpage \n \
%% Titulní strana - konec%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
%% Prohlaseni zacatek%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
\\rule[10pt]{16cm}{0.4pt}\\ \n \
\\vspace{20cm} \n \
\\begin{flushleft} \n \
\\textsf{\\textbf{Prohlášení}} \n \
\\par\\end{flushleft} \n \
\\begin{flushleft} \n \
Prohlašuji, že jsem tuto ročníkovou práci vypracoval samostatně s použitím uvedené literatury a pramenů. \n \
\\par\\end{flushleft} \n \
%%\\begin{flushleft} \n \
%%\\ Jakub Macků \n \
%%\\par\\end{flushleft} \n \
%%\\linebreak \n \
\\begin{flushleft} \n \
Ve Šlapanicích dne:  \n \
\\hspace{6cm} \n \
Podpis: \n \
\\par\\end{flushleft} \n \
\\newpage \n \
%% Prohlaseni konec%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
%% Podekovani zacatek%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
\\rule[10pt]{16cm}{0.4pt}\\ \n \
\\vspace{20cm} \n \
\\begin{flushleft} \n \
\\textsf{\\textbf{Poděkování}} \n \
\\par\\end{flushleft} \n \
Chtěl bych poděkovat vedoucímu práce Mgr. Romanu Ondrůškovi a Ing. Jiřímu Macků za pomoc při tvorbě a realizaci této ročníkové práce. \n \
\\newpage \n \
%% Podekovani konec%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
%% Anotace zacatek%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% \n \
\\rule[10pt]{16cm}{0.4pt}\\ \n \
\\vspace{16cm} \n \
\\begin{flushleft} \n \
\\textsf{\\textbf{Anotace}} \n \
\\par\\end{flushleft} \n \
Tato práce se zabývá sestavením digitálního mikroskopu, který by sloužil k pořízení, zpracování a uložení mikroskopového obrazu. Digitální mikroskop bude tvořen běžným optickým mikroskopem a digitální kamerou ovládanou mikropočítačem Raspberry Pi. Uživatelské prostředí bude ve formě webové aplikace.  \n \
\\begin{flushleft} \n \
\\textsf{\\textbf{Abstract}} \n \
\\par\\end{flushleft} \n \
This work deals with assembling digital microscope for taking, processing and saving of microscopic pictures. Digital microscope will be created from normal optical microscope and digital camera controled by microcomputer Raspberry Pi. User interface will be created in form of web application.\n \
\\begin{flushleft} \n \
\\textsf{\\textbf{Klíčová slova}} \n \
\\par\\end{flushleft} \n \
Programování, Python, Raspberry Pi, mikroskop, digitalizace, zpracování obrazu. \n \
\\newpage \n \
%% Anotace konec \n \
\\widowpenalty=10000 \n \
\\clubpenalty=10000 \n \
%%\\parindent=0.5cm',
#konec

# Latex figure (float) alignment
#'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  (master_doc, 'micro.tex', u'Dokumentace Micro',
   u'Jakub Macků', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'Micro', u'micro Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  (master_doc, 'micro', u'micro Documentation',
   author, 'micro', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False
